/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "vae_constants.h"



const vaeConstants g_vae_constants;

vaeConstants::vaeConstants() {
}



