/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef vae_CONSTANTS_H
#define vae_CONSTANTS_H

#include "vae_types.h"



class vaeConstants {
 public:
  vaeConstants();

};

extern const vaeConstants g_vae_constants;



#endif
