#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


class VaeDbInternalError < ::Thrift::Exception
  include ::Thrift::Struct
  def initialize(message=nil)
    super()
    self.message = message
  end

  MESSAGE = 1

  ::Thrift::Struct.field_accessor self, :message
  FIELDS = {
    MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbQueryError < ::Thrift::Exception
  include ::Thrift::Struct
  def initialize(message=nil)
    super()
    self.message = message
  end

  MESSAGE = 1

  ::Thrift::Struct.field_accessor self, :message
  FIELDS = {
    MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeSyntaxError < ::Thrift::Exception
  include ::Thrift::Struct
  def initialize(message=nil)
    super()
    self.message = message
  end

  MESSAGE = 1

  ::Thrift::Struct.field_accessor self, :message
  FIELDS = {
    MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbContext
  include ::Thrift::Struct
  ID = 1
  STRUCTURE_ID = 2
  TYPE = 3
  PERMALINK = 4
  DATA = 5
  DATAMAP = 6

  ::Thrift::Struct.field_accessor self, :id, :structure_id, :type, :permalink, :data, :dataMap
  FIELDS = {
    ID => {:type => ::Thrift::Types::I32, :name => 'id'},
    STRUCTURE_ID => {:type => ::Thrift::Types::I32, :name => 'structure_id'},
    TYPE => {:type => ::Thrift::Types::STRING, :name => 'type'},
    PERMALINK => {:type => ::Thrift::Types::STRING, :name => 'permalink'},
    DATA => {:type => ::Thrift::Types::STRING, :name => 'data'},
    DATAMAP => {:type => ::Thrift::Types::MAP, :name => 'dataMap', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRING}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbCreateInfo
  include ::Thrift::Struct
  STRUCTURE_ID = 1
  ROW_ID = 2

  ::Thrift::Struct.field_accessor self, :structure_id, :row_id
  FIELDS = {
    STRUCTURE_ID => {:type => ::Thrift::Types::I32, :name => 'structure_id'},
    ROW_ID => {:type => ::Thrift::Types::I32, :name => 'row_id'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbStructure
  include ::Thrift::Struct
  ID = 1
  NAME = 2
  TYPE = 3
  PERMALINK = 4

  ::Thrift::Struct.field_accessor self, :id, :name, :type, :permalink
  FIELDS = {
    ID => {:type => ::Thrift::Types::I32, :name => 'id'},
    NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
    TYPE => {:type => ::Thrift::Types::STRING, :name => 'type'},
    PERMALINK => {:type => ::Thrift::Types::STRING, :name => 'permalink'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbResponseForContext
  include ::Thrift::Struct
  CONTEXTS = 1
  TOTALITEMS = 2

  ::Thrift::Struct.field_accessor self, :contexts, :totalItems
  FIELDS = {
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => VaeDbContext}},
    TOTALITEMS => {:type => ::Thrift::Types::I32, :name => 'totalItems'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbResponse
  include ::Thrift::Struct
  ID = 1
  CONTEXTS = 2

  ::Thrift::Struct.field_accessor self, :id, :contexts
  FIELDS = {
    ID => {:type => ::Thrift::Types::I32, :name => 'id'},
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => VaeDbResponseForContext}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbCreateInfoResponse
  include ::Thrift::Struct
  CONTEXTS = 1

  ::Thrift::Struct.field_accessor self, :contexts
  FIELDS = {
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => VaeDbCreateInfo}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbDataForContext
  include ::Thrift::Struct
  DATA = 1

  ::Thrift::Struct.field_accessor self, :data
  FIELDS = {
    DATA => {:type => ::Thrift::Types::MAP, :name => 'data', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRING}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbDataResponse
  include ::Thrift::Struct
  CONTEXTS = 1

  ::Thrift::Struct.field_accessor self, :contexts
  FIELDS = {
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => VaeDbDataForContext}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

class VaeDbStructureResponse
  include ::Thrift::Struct
  CONTEXTS = 1

  ::Thrift::Struct.field_accessor self, :contexts
  FIELDS = {
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => VaeDbStructure}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

end

