#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class VaeDbInternalError < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  def initialize(message=nil)
    super()
    self.message = message
  end

  MESSAGE = 1

  FIELDS = {
    MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbQueryError < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  def initialize(message=nil)
    super()
    self.message = message
  end

  MESSAGE = 1

  FIELDS = {
    MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeSyntaxError < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  def initialize(message=nil)
    super()
    self.message = message
  end

  MESSAGE = 1

  FIELDS = {
    MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbContext
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ID = 1
  STRUCTURE_ID = 2
  TYPE = 3
  PERMALINK = 4
  DATA = 5
  DATAMAP = 6

  FIELDS = {
    ID => {:type => ::Thrift::Types::I32, :name => 'id'},
    STRUCTURE_ID => {:type => ::Thrift::Types::I32, :name => 'structure_id'},
    TYPE => {:type => ::Thrift::Types::STRING, :name => 'type'},
    PERMALINK => {:type => ::Thrift::Types::STRING, :name => 'permalink'},
    DATA => {:type => ::Thrift::Types::STRING, :name => 'data'},
    DATAMAP => {:type => ::Thrift::Types::MAP, :name => 'dataMap', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRING}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbCreateInfo
  include ::Thrift::Struct, ::Thrift::Struct_Union
  STRUCTURE_ID = 1
  ROW_ID = 2

  FIELDS = {
    STRUCTURE_ID => {:type => ::Thrift::Types::I32, :name => 'structure_id'},
    ROW_ID => {:type => ::Thrift::Types::I32, :name => 'row_id'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbStructure
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ID = 1
  NAME = 2
  TYPE = 3
  PERMALINK = 4

  FIELDS = {
    ID => {:type => ::Thrift::Types::I32, :name => 'id'},
    NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
    TYPE => {:type => ::Thrift::Types::STRING, :name => 'type'},
    PERMALINK => {:type => ::Thrift::Types::STRING, :name => 'permalink'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbResponseForContext
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CONTEXTS = 1
  TOTALITEMS = 2

  FIELDS = {
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => ::VaeDbContext}},
    TOTALITEMS => {:type => ::Thrift::Types::I32, :name => 'totalItems'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbResponse
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ID = 1
  CONTEXTS = 2

  FIELDS = {
    ID => {:type => ::Thrift::Types::I32, :name => 'id'},
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => ::VaeDbResponseForContext}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbCreateInfoResponse
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CONTEXTS = 1

  FIELDS = {
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => ::VaeDbCreateInfo}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbDataForContext
  include ::Thrift::Struct, ::Thrift::Struct_Union
  DATA = 1

  FIELDS = {
    DATA => {:type => ::Thrift::Types::MAP, :name => 'data', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRING}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbDataResponse
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CONTEXTS = 1

  FIELDS = {
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => ::VaeDbDataForContext}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbStructureResponse
  include ::Thrift::Struct, ::Thrift::Struct_Union
  CONTEXTS = 1

  FIELDS = {
    CONTEXTS => {:type => ::Thrift::Types::LIST, :name => 'contexts', :element => {:type => ::Thrift::Types::STRUCT, :class => ::VaeDbStructure}}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class VaeDbOpenSessionResponse
  include ::Thrift::Struct, ::Thrift::Struct_Union
  SESSION_ID = 1
  GENERATION = 2

  FIELDS = {
    SESSION_ID => {:type => ::Thrift::Types::I32, :name => 'session_id'},
    GENERATION => {:type => ::Thrift::Types::I32, :name => 'generation'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

