#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'vae_types'

module VaeDb
  class Client
    include ::Thrift::Client

    def ping()
      send_ping()
      return recv_ping()
    end

    def send_ping()
      send_message('ping', Ping_args)
    end

    def recv_ping()
      result = receive_message(Ping_result)
      return result.success unless result.success.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'ping failed: unknown result')
    end

    def closeSession(session_id, secret_key)
      send_closeSession(session_id, secret_key)
      recv_closeSession()
    end

    def send_closeSession(session_id, secret_key)
      send_message('closeSession', CloseSession_args, :session_id => session_id, :secret_key => secret_key)
    end

    def recv_closeSession()
      result = receive_message(CloseSession_result)
      raise result.e unless result.e.nil?
      return
    end

    def createInfo(session_id, response_id, query)
      send_createInfo(session_id, response_id, query)
      return recv_createInfo()
    end

    def send_createInfo(session_id, response_id, query)
      send_message('createInfo', CreateInfo_args, :session_id => session_id, :response_id => response_id, :query => query)
    end

    def recv_createInfo()
      result = receive_message(CreateInfo_result)
      return result.success unless result.success.nil?
      raise result.ie unless result.ie.nil?
      raise result.qe unless result.qe.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'createInfo failed: unknown result')
    end

    def data(session_id, response_id)
      send_data(session_id, response_id)
      return recv_data()
    end

    def send_data(session_id, response_id)
      send_message('data', Data_args, :session_id => session_id, :response_id => response_id)
    end

    def recv_data()
      result = receive_message(Data_result)
      return result.success unless result.success.nil?
      raise result.ie unless result.ie.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'data failed: unknown result')
    end

    def get(session_id, response_id, query, options)
      send_get(session_id, response_id, query, options)
      return recv_get()
    end

    def send_get(session_id, response_id, query, options)
      send_message('get', Get_args, :session_id => session_id, :response_id => response_id, :query => query, :options => options)
    end

    def recv_get()
      result = receive_message(Get_result)
      return result.success unless result.success.nil?
      raise result.ie unless result.ie.nil?
      raise result.qe unless result.qe.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'get failed: unknown result')
    end

    def openSession(site, secret_key, staging_mode, suggested_session_id)
      send_openSession(site, secret_key, staging_mode, suggested_session_id)
      return recv_openSession()
    end

    def send_openSession(site, secret_key, staging_mode, suggested_session_id)
      send_message('openSession', OpenSession_args, :site => site, :secret_key => secret_key, :staging_mode => staging_mode, :suggested_session_id => suggested_session_id)
    end

    def recv_openSession()
      result = receive_message(OpenSession_result)
      return result.success unless result.success.nil?
      raise result.e unless result.e.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'openSession failed: unknown result')
    end

    def resetSite(site, secret_key)
      send_resetSite(site, secret_key)
      recv_resetSite()
    end

    def send_resetSite(site, secret_key)
      send_message('resetSite', ResetSite_args, :site => site, :secret_key => secret_key)
    end

    def recv_resetSite()
      result = receive_message(ResetSite_result)
      raise result.e unless result.e.nil?
      return
    end

    def structure(session_id, response_id)
      send_structure(session_id, response_id)
      return recv_structure()
    end

    def send_structure(session_id, response_id)
      send_message('structure', Structure_args, :session_id => session_id, :response_id => response_id)
    end

    def recv_structure()
      result = receive_message(Structure_result)
      return result.success unless result.success.nil?
      raise result.ie unless result.ie.nil?
      raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'structure failed: unknown result')
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_ping(seqid, iprot, oprot)
      args = read_args(iprot, Ping_args)
      result = Ping_result.new()
      result.success = @handler.ping()
      write_result(result, oprot, 'ping', seqid)
    end

    def process_closeSession(seqid, iprot, oprot)
      args = read_args(iprot, CloseSession_args)
      result = CloseSession_result.new()
      begin
        @handler.closeSession(args.session_id, args.secret_key)
      rescue VaeDbInternalError => e
        result.e = e
      end
      write_result(result, oprot, 'closeSession', seqid)
    end

    def process_createInfo(seqid, iprot, oprot)
      args = read_args(iprot, CreateInfo_args)
      result = CreateInfo_result.new()
      begin
        result.success = @handler.createInfo(args.session_id, args.response_id, args.query)
      rescue VaeDbInternalError => ie
        result.ie = ie
      rescue VaeDbQueryError => qe
        result.qe = qe
      end
      write_result(result, oprot, 'createInfo', seqid)
    end

    def process_data(seqid, iprot, oprot)
      args = read_args(iprot, Data_args)
      result = Data_result.new()
      begin
        result.success = @handler.data(args.session_id, args.response_id)
      rescue VaeDbInternalError => ie
        result.ie = ie
      end
      write_result(result, oprot, 'data', seqid)
    end

    def process_get(seqid, iprot, oprot)
      args = read_args(iprot, Get_args)
      result = Get_result.new()
      begin
        result.success = @handler.get(args.session_id, args.response_id, args.query, args.options)
      rescue VaeDbInternalError => ie
        result.ie = ie
      rescue VaeDbQueryError => qe
        result.qe = qe
      end
      write_result(result, oprot, 'get', seqid)
    end

    def process_openSession(seqid, iprot, oprot)
      args = read_args(iprot, OpenSession_args)
      result = OpenSession_result.new()
      begin
        result.success = @handler.openSession(args.site, args.secret_key, args.staging_mode, args.suggested_session_id)
      rescue VaeDbInternalError => e
        result.e = e
      end
      write_result(result, oprot, 'openSession', seqid)
    end

    def process_resetSite(seqid, iprot, oprot)
      args = read_args(iprot, ResetSite_args)
      result = ResetSite_result.new()
      begin
        @handler.resetSite(args.site, args.secret_key)
      rescue VaeDbInternalError => e
        result.e = e
      end
      write_result(result, oprot, 'resetSite', seqid)
    end

    def process_structure(seqid, iprot, oprot)
      args = read_args(iprot, Structure_args)
      result = Structure_result.new()
      begin
        result.success = @handler.structure(args.session_id, args.response_id)
      rescue VaeDbInternalError => ie
        result.ie = ie
      end
      write_result(result, oprot, 'structure', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class Ping_args
    include ::Thrift::Struct

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Ping_result
    include ::Thrift::Struct
    SUCCESS = 0

    ::Thrift::Struct.field_accessor self, :success
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::BYTE, :name => 'success'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class CloseSession_args
    include ::Thrift::Struct
    SESSION_ID = 1
    SECRET_KEY = 2

    ::Thrift::Struct.field_accessor self, :session_id, :secret_key
    FIELDS = {
      SESSION_ID => {:type => ::Thrift::Types::I32, :name => 'session_id'},
      SECRET_KEY => {:type => ::Thrift::Types::STRING, :name => 'secret_key'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class CloseSession_result
    include ::Thrift::Struct
    E = 1

    ::Thrift::Struct.field_accessor self, :e
    FIELDS = {
      E => {:type => ::Thrift::Types::STRUCT, :name => 'e', :class => VaeDbInternalError}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class CreateInfo_args
    include ::Thrift::Struct
    SESSION_ID = 1
    RESPONSE_ID = 2
    QUERY = 3

    ::Thrift::Struct.field_accessor self, :session_id, :response_id, :query
    FIELDS = {
      SESSION_ID => {:type => ::Thrift::Types::I32, :name => 'session_id'},
      RESPONSE_ID => {:type => ::Thrift::Types::I32, :name => 'response_id'},
      QUERY => {:type => ::Thrift::Types::STRING, :name => 'query'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class CreateInfo_result
    include ::Thrift::Struct
    SUCCESS = 0
    IE = 1
    QE = 2

    ::Thrift::Struct.field_accessor self, :success, :ie, :qe
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => VaeDbCreateInfoResponse},
      IE => {:type => ::Thrift::Types::STRUCT, :name => 'ie', :class => VaeDbInternalError},
      QE => {:type => ::Thrift::Types::STRUCT, :name => 'qe', :class => VaeDbQueryError}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Data_args
    include ::Thrift::Struct
    SESSION_ID = 1
    RESPONSE_ID = 2

    ::Thrift::Struct.field_accessor self, :session_id, :response_id
    FIELDS = {
      SESSION_ID => {:type => ::Thrift::Types::I32, :name => 'session_id'},
      RESPONSE_ID => {:type => ::Thrift::Types::I32, :name => 'response_id'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Data_result
    include ::Thrift::Struct
    SUCCESS = 0
    IE = 1

    ::Thrift::Struct.field_accessor self, :success, :ie
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => VaeDbDataResponse},
      IE => {:type => ::Thrift::Types::STRUCT, :name => 'ie', :class => VaeDbInternalError}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_args
    include ::Thrift::Struct
    SESSION_ID = 1
    RESPONSE_ID = 2
    QUERY = 3
    OPTIONS = 4

    ::Thrift::Struct.field_accessor self, :session_id, :response_id, :query, :options
    FIELDS = {
      SESSION_ID => {:type => ::Thrift::Types::I32, :name => 'session_id'},
      RESPONSE_ID => {:type => ::Thrift::Types::I32, :name => 'response_id'},
      QUERY => {:type => ::Thrift::Types::STRING, :name => 'query'},
      OPTIONS => {:type => ::Thrift::Types::MAP, :name => 'options', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRING}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Get_result
    include ::Thrift::Struct
    SUCCESS = 0
    IE = 1
    QE = 2

    ::Thrift::Struct.field_accessor self, :success, :ie, :qe
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => VaeDbResponse},
      IE => {:type => ::Thrift::Types::STRUCT, :name => 'ie', :class => VaeDbInternalError},
      QE => {:type => ::Thrift::Types::STRUCT, :name => 'qe', :class => VaeDbQueryError}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class OpenSession_args
    include ::Thrift::Struct
    SITE = 1
    SECRET_KEY = 2
    STAGING_MODE = 3
    SUGGESTED_SESSION_ID = 4

    ::Thrift::Struct.field_accessor self, :site, :secret_key, :staging_mode, :suggested_session_id
    FIELDS = {
      SITE => {:type => ::Thrift::Types::STRING, :name => 'site'},
      SECRET_KEY => {:type => ::Thrift::Types::STRING, :name => 'secret_key'},
      STAGING_MODE => {:type => ::Thrift::Types::BOOL, :name => 'staging_mode'},
      SUGGESTED_SESSION_ID => {:type => ::Thrift::Types::I32, :name => 'suggested_session_id'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class OpenSession_result
    include ::Thrift::Struct
    SUCCESS = 0
    E = 1

    ::Thrift::Struct.field_accessor self, :success, :e
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::I32, :name => 'success'},
      E => {:type => ::Thrift::Types::STRUCT, :name => 'e', :class => VaeDbInternalError}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class ResetSite_args
    include ::Thrift::Struct
    SITE = 1
    SECRET_KEY = 2

    ::Thrift::Struct.field_accessor self, :site, :secret_key
    FIELDS = {
      SITE => {:type => ::Thrift::Types::STRING, :name => 'site'},
      SECRET_KEY => {:type => ::Thrift::Types::STRING, :name => 'secret_key'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class ResetSite_result
    include ::Thrift::Struct
    E = 1

    ::Thrift::Struct.field_accessor self, :e
    FIELDS = {
      E => {:type => ::Thrift::Types::STRUCT, :name => 'e', :class => VaeDbInternalError}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Structure_args
    include ::Thrift::Struct
    SESSION_ID = 1
    RESPONSE_ID = 2

    ::Thrift::Struct.field_accessor self, :session_id, :response_id
    FIELDS = {
      SESSION_ID => {:type => ::Thrift::Types::I32, :name => 'session_id'},
      RESPONSE_ID => {:type => ::Thrift::Types::I32, :name => 'response_id'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

  class Structure_result
    include ::Thrift::Struct
    SUCCESS = 0
    IE = 1

    ::Thrift::Struct.field_accessor self, :success, :ie
    FIELDS = {
      SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => VaeDbStructureResponse},
      IE => {:type => ::Thrift::Types::STRUCT, :name => 'ie', :class => VaeDbInternalError}
    }

    def struct_fields; FIELDS; end

    def validate
    end

  end

end

